//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevopsWithMvcApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeSheet
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> TaskDate { get; set; }
        public string Source { get; set; }
        public string Sprint { get; set; }
        public string PBId { get; set; }
        public string HdName { get; set; }
        public Nullable<int> WorkorderType { get; set; }
        public string Description { get; set; }
        public Nullable<int> Hours { get; set; }
        public Nullable<System.DateTime> SourceEmailDate { get; set; }
    }
}
