//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCrud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeAcademic
    {
        public int Acdid { get; set; }
        public Nullable<int> RefempId { get; set; }
        public string HSC { get; set; }
        public string SSC { get; set; }
        public string Graduate { get; set; }
        public string PostGraduate { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
